import './global.css';
import Header from "../src/components/Header";
import Footer from "../src/components/Footer";
import React from "react";
import Provider from "../src/store/provider";
import {useSelector} from "react-redux";


export const metadata = {
  title: 'Rain Media Web Project',
  description: 'Generated by ardaninsaturnu',
}

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
    <head>
      <title>{metadata.title}</title>
    </head>
    <body>
      <Provider>
        <Header/>
        {children}
        <Footer/>
      </Provider>
    </body>
    </html>
  )
}
