import './global.css';
import Navigation from "../src/components/Header/Navigation";

export const metadata = {
  title: 'Rain Media Web Project',
  description: 'Generated by ardaninsaturnu',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <body>
      <Navigation/>
      {children}
    </body>
    </html>
  )
}
